nodeLinker: node-modules

enableGlobalCache: true
compressionLevel: mixed

logFilters:
  - code: YN0013
    level: discard
  - code: YN0060
    level: discard

progressBarStyle: patrick
enableStrictSsl: true
